spring:
  application:
    name: catalog

  datasource:
    url: jdbc:postgresql://172.26.207.240:5432/catalogdb
    username: cataloguser
    password: catalogpass
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: 172.26.207.240
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: my-super-secret-key-that-is-at-least-32-characters-long
  expiration-ms: 86400000

server:
  port: 8080

aws:
  region: us-east-1
  sqs:
    queue-url: https://sqs.us-east-1.amazonaws.com/227769752968/order-notifications